# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mjau < Formula
  desc ""
  homepage "https://getmjau.com"
  version "0.0.10"

  on_macos do
    url "https://github.com/getmjau/mjau/releases/download/v0.0.10/mjau_0.0.10_Darwin_all.tar.gz"
    sha256 "cfe3db745c9936071197738cafc4f1e98ddf7eb6237db5eaef125716a60e9acd"

    def install
      bin.install "mjau"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getmjau/mjau/releases/download/v0.0.10/mjau_0.0.10_Linux_x86_64.tar.gz"
        sha256 "a993218cf2f933cc86c3e9df2c5934c94a1cf9a7a3037919e73b156e73c38ded"

        def install
          bin.install "mjau"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getmjau/mjau/releases/download/v0.0.10/mjau_0.0.10_Linux_arm64.tar.gz"
        sha256 "e885e6403cbe38dadbe84b713269a7953f806811c977ab7fd7cf0fdd50bab79f"

        def install
          bin.install "mjau"
        end
      end
    end
  end
end
