# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mjau < Formula
  desc ""
  homepage "https://getmjau.dev"
  version "0.0.11"

  on_macos do
    url "https://github.com/getmjau/mjau/releases/download/v0.0.11/mjau_0.0.11_Darwin_all.tar.gz"
    sha256 "746fc82dbfe98fb59d6e4045674e135c50a0d5f9c513ebd70f666dc2a2464813"

    def install
      bin.install "mjau"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getmjau/mjau/releases/download/v0.0.11/mjau_0.0.11_Linux_x86_64.tar.gz"
        sha256 "ca56905f8dbebb0afc97f6a24f656b2883f233d6a2a4c3cd875112ece6220324"

        def install
          bin.install "mjau"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getmjau/mjau/releases/download/v0.0.11/mjau_0.0.11_Linux_arm64.tar.gz"
        sha256 "f8e2fe94d61f79d7bc1b3da49dd86b9632c5489a44a3c8ddf4724141c9106361"

        def install
          bin.install "mjau"
        end
      end
    end
  end
end
